package='com.longgui.auth.factor.saml2'
name='SAML2.0认证因素'
version='1.1'
labels=['SAML2.0', 'auth_factor']
homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_auth_factor_saml2/'
logo=''
author='guancyxx@guancyxx.cn'