version: '3.5'

services:
  portal:
    image: nginx:alpine
    container_name: ${INSTANCE}-portal
    restart: always
    networks:
      - arkid
    ports:
      - ${HTTP_PORT}:80
    depends_on:
      - be
      - fe
    volumes:
      - ${WORKSPACE}/portal.conf:/etc/nginx/conf.d/default.conf

  be:
    image: longguikeji/arkid:1.4.4
    container_name: ${INSTANCE}-be
    sysctls:
      - net.core.somaxconn=65535
    restart: always
    networks:
      - arkid
    depends_on:
      - db
    volumes:
      - ${WORKSPACE}/be/settings.py:/var/oneid/settings_local.py
      - ${WORKSPACE}/be/upload:/var/oneid/upload
      - ${WORKSPACE}/be/plugins:/var/oneid/plugins

  fe:
    image: longguikeji/arkid-fe:1.4.2
    container_name: ${INSTANCE}-fe
    restart: always
    networks:
      - arkid

  db:
    image: mysql:5.7
    container_name: ${INSTANCE}-db
    restart: always
    networks:
      - arkid
    environment:
      - MYSQL_DATABASE=arkid
      - MYSQL_ROOT_PASSWORD=${SQL_PWD}
    volumes:
      - ${WORKSPACE}/db/data:/var/lib/mysql
      - ${WORKSPACE}/db/config:/etc/mysql/conf.d
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  ldap:
    image: longguikeji/ark-sql-ldap:1.3.0
    container_name: ${INSTANCE}-ldap
    restart: always
    networks:
      - arkid
    depends_on:
      - be
    ports:
      - ${LDAP_PORT}:389
    environment:
      - SQL_HOST=${INSTANCE}-db
      - SQL_PORT=3306
      - SQL_USER=root
      - SQL_PWD=${SQL_PWD}
      - LDAP_PASSWORD=${LDAP_PASSWORD}
      - SQL_DB=arkid
      - BACKEND=sql
      - SLAPD_NOFILE_SOFT=10000

  redis:
    image: redis:5.0.3
    container_name: ${INSTANCE}-redis
    restart: always
    networks:
      - arkid

networks:
  arkid:
    name: ${INSTANCE}
    driver: bridge
