    package='com.longgui.app.proxy.nginx'
    name='Nginx应用入口代理'
    version='1.6'
    labels='app-proxy-nginx'
    homepage='http://longguikeji.gitee.io/arkid/%20%E5%85%B6%E5%AE%83%E6%8F%92%E4%BB%B6/com_longgui_app_proxy_nginx/'
    logo=''
    author='fanhe@longguikeji.com'
