version: '3.5'

services:
  portal:
    image: nginx:alpine
    container_name: ${INSTANCE}-portal
    restart: always
    networks:
      - arkid
    ports:
      - 8989:80
    depends_on:
      - be
      - fe
    volumes:
      - ${WORKSPACE}/portal.conf:/etc/nginx/conf.d/default.conf

  be:
    image: longguikeji/arkid:v2dev-101
    container_name: ${INSTANCE}-be
    sysctls:
      - net.core.somaxconn=65535
    restart: always
    working_dir: /var/arkid
    entrypoint: ["tail"]
    command: ["-f", "/dev/null"]
    environment:
      - MYSQL_HOST=${INSTANCE}-db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=arkid
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - REDIS_HOST=${INSTANCE}-redis
    networks:
      - arkid
    depends_on:
      - db
    volumes:
      - ../../:/var/arkid
      - ${WORKSPACE}/settings.py:/var/arkid/settings_local.py
      - ${WORKSPACE}/arkid.toml:/var/arkid/arkid.local.toml
      - ${WORKSPACE}/supervisord.conf:/var/arkid/supervisord.conf
      - ${WORKSPACE}/be/cert:/var/arkid/djangosaml2idp/certificates
      - ${WORKSPACE}/be/saml2config:/var/arkid/djangosaml2idp/saml2_config

  # 开发前端的话用这个
  fe:
    image: node:12-buster
    container_name: arkid-fe
    restart: always
    working_dir: /root/workspace/arkid-fe
    command: sh -c "yarn install --ignore-engines --frozen-lockfile --non-interactive && tail -f /dev/null"
    networks:
      - arkid
    volumes:
      ## 这个路径是arkid-fe所在的目录
      - ../../../arkid-frontend:/root/workspace/arkid-fe

  # 不开发前段的话，放开这个
  # fe:
  #   image: longguikeji/arkid-fe:v2dev
  #   container_name: ${INSTANCE}-fe
  #   restart: always
  #   networks:
  #     - arkid
  #   volumes:
  #     - ${WORKSPACE}/fe.conf:/etc/nginx/conf.d/default.conf

  db:
    image: mysql:5.7
    container_name: ${INSTANCE}-db
    restart: always
    networks:
      - arkid
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=arkid
    volumes:
      - ${WORKSPACE}/db/data:/var/lib/mysql
      - ${WORKSPACE}/db/config:/etc/mysql/conf.d
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"

  ldap:
    image: longguikeji/arkid_ldap_server:v2dev
    container_name: ${INSTANCE}-ldap
    restart: always
    networks:
      - arkid
    depends_on:
      - be
    ports:
      - ${LDAP_PORT}:1389
    volumes:
      - ${WORKSPACE}/ldapjs-config.json:/usr/src/app/config.json
    environment:
      - TZ=Asia/Shanghai

  redis:
    image: redis:5.0.3
    container_name: ${INSTANCE}-redis
    restart: always
    networks:
      - arkid

networks:
  arkid:
    name: ${INSTANCE}
    driver: bridge
