name: arkid v2 cicd
on:
  push:
    branches:
      - v2-dev
jobs:
  dev2test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login harbor
      uses: docker/login-action@v1 
      with:
        registry: harbor.longguikeji.com
        username: ${{ secrets.HARBORUSER }}
        password: ${{ secrets.HARBORPWD }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERHUBPWD }}
    - id: get-short-id
      run: |
        id=$(echo ${{github.sha}})
        echo "::set-output name=id::${id: 0 :8}"
    - run: echo "${{steps.get-short-id.outputs.id}}"
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: |
          harbor.longguikeji.com/ark-releases/arkid:v2dev-${{ github.run_number }}-${{steps.get-short-id.outputs.id}}
          longguikeji/arkid:v2dev-${{ github.run_number }}
          longguikeji/arkid:v2dev
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: # defaults to latest kubectl binary version
        config: ${{ secrets.KUBE_CONFIG_HW }}
        command: -n arkidv2 --insecure-skip-tls-verify=true set image --record deployment/arkidv2-be arkid-be=harbor.longguikeji.com/ark-releases/arkid:v2dev-${{ github.run_number }}-${{steps.get-short-id.outputs.id}}
    - name: Feishu 报忧
      if: ${{ failure() }}
      uses: wangsijie/feishu-bot@v1
      with:
        uuid: ${{ secrets.FEISHU_UUID }}
        data: |
          {"msg_type":"post","content":{"post":{"zh_cn":{"title":"${{ github.event.repository.name }}流水线状态通知",
          "content":[[{"tag":"text","text":"${{ github.event.repository.name }} 项目流水线有更新: "},
          {"tag":"a","text":"${{ github.event.ref }}分支构建失败，点击查看具体日志","href":"${{ github.event.commits.url }}"}]]}}}}
    - name: Feishu 报喜
      if: ${{ success() }}
      uses: wangsijie/feishu-bot@v1
      with:
        uuid: ${{ secrets.FEISHU_UUID }}
        data: |
          {"msg_type":"post","content":{"post":{"zh_cn":{"title": "${{ github.event.repository.name }}流水线状态通知",
          "content":[[{"tag":"text","text":"${{ github.event.repository.name }} 项目流水线有更新: "},
          {"tag":"a","text":"${{ github.event.ref }}分支构建并部署成功，点击查看部署后的效果","href":"http://arkid.vtwo.longguikeji.com/"}]]}}}}
