name: arkid v2.5 cicd

on:
  workflow_dispatch:
  push:
    branches:
      - v2.5-dev
    paths-ignore:
      - 'docs/**'
      - 'kustomize/**'
      - 'README.md'
      - '.github/**'
jobs:
  dev2test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login harbor
      uses: docker/login-action@v1
      with:
        registry: harbor.longguikeji.com
        username: ${{ secrets.HARBORUSER }}
        password: ${{ secrets.HARBORPWD }}
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUBUSERNAME }}
        password: ${{ secrets.DOCKERHUBPWD }}
    - id: get-short-id
      run: |
        id=$(echo ${{github.sha}})
        echo "::set-output name=id::${id: 0 :8}"
    - run: echo "${{steps.get-short-id.outputs.id}}"
    - id: set-pip
      run: |
        sed -i "s@https://mirrors.aliyun.com/pypi/simple@https://pypi.python.org/simple@g" requirements.txt;
        sed -i "s@https://mirrors.aliyun.com/pypi/simple@https://pypi.python.org/simple@g" requirements-dev.txt;
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        platforms: linux/amd64
        build-args: |
          DEBIAN=http://deb.debian.org/debian
          DEBIANSRT=http://security.debian.org/debian-security
          PIP="https://pypi.python.org/simple"
        push: true
        tags: |
          ${{ secrets.ARK_DEV }}/arkid:v25dev-${{ github.run_number }}-${{steps.get-short-id.outputs.id}}
          ${{ secrets.ARK_DEV }}/arkid:v25dev-${{ github.run_number }}
          ${{ secrets.ARK_DEV }}/arkid:v25dev
          longguikeji/arkid:v25dev-${{ github.run_number }}-${{steps.get-short-id.outputs.id}}
          longguikeji/arkid:v25dev-${{ github.run_number }}
          longguikeji/arkid:v25dev
    - name: deploy to cluster
      uses: steebchen/kubectl@v2.0.0
      with: # defaults to latest kubectl binary version
        config: ${{ secrets.KUBE_CONFIG_HW }}
        command: -n dev-arkidv2 --insecure-skip-tls-verify=true set image --record deployment/dev-arkidv2-be arkid-be=${{ secrets.ARK_DEV }}/arkid:v25dev-${{ github.run_number }}