name: ci

on:
  push:
    branches:
      - 'feature-*'
      - 'dev/*'
    paths-ignore:
      - 'docs/**'
      - 'kustomize/**'
      - 'README.md'
      - '.github/**'
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: 安装依赖
      id: build_deps
      continue-on-error: true
      run: docker build --target build_deps -t arkid:build_deps .
    - name: 样式检查
      id: run_lint
      continue-on-error: true
      run: docker build --target run_lint -t arkid:run_lint .
    - name: build
      id: build
      continue-on-error: true
      run: docker build --target build -t arkid:build .
    - name: Feishu 报忧
      if: ${{ failure() }}
      uses: wangsijie/feishu-bot@v1
      with:
        uuid: ${{ secrets.FEISHU_UUID }}
        data: |
          {"msg_type":"post","content":{"post":{"zh_cn":{"title":"${{ github.event.repository.name }}流水线状态通知",
          "content":[[{"tag":"text","text":"${{ github.event.repository.name }} 项目流水线有更新: "},
          {"tag":"a","text":"${{ github.event.ref }}分支 ci构建失败","href":"https://github.com/${{ github.repository }}/actions/workflows/status.yml"}]]}}}}
    - name: Feishu 报喜
      if: ${{ success() }}
      uses: wangsijie/feishu-bot@v1
      with:
        uuid: ${{ secrets.FEISHU_UUID }}
        data: |
          {"msg_type":"post","content":{"post":{"zh_cn":{"title": "${{ github.event.repository.name }}流水线状态通知",
          "content":[[{"tag":"text","text":"${{ github.event.repository.name }} 项目流水线有更新: "},
          {"tag":"a","text":"${{ github.event.ref }}分支 ci构建成功","href":"http://arkid.vtwo.longguikeji.com/"}]]}}}}
          